tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        custom_coding_standard:
            ruleset_path: phpcs_ruleset.xml
        security_vulnerabilities: false
        unused_parameters: false
