tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    # Folders which we should not check
    excluded_paths:
        - 'cert/*'
        - 'compat/*'
        - 'doc/*'
        - 'mail/*'
        - 'public/*'
        - 'templates/*'
        - 'tests/*'
        - 'tools/*'
checks:
    php:
        # Use custom PHPCS ruleset
        custom_coding_standard:
            ruleset_path: phpcs_ruleset.xml
        # Disable some of default checks
        security_vulnerabilities: false
        no_commented_out_code: false
        avoid_superglobals: false
        no_eval: false
        # it looks that this parameter has no effect on scrutinizer :(
        unused_variables: false
        unused_properties: false
        unused_parameters: false
        unused_methods: false
