language: php
php:
  - 5.5
  - 5.4
  - 5.3
script: ./tests/run_tests.sh
notifications:
  irc: 
    channels:
      - "chat.freenode.net#atk4"
    on_success: always
    on_failure: always
  email: false
