language: php
php:
  - 5.5
  - 5.4
  - 5.3
#before_script: 
#  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
#  - (cd tests; composer install)
#script: (cd tests; php ../mageekguy.atoum.phar -f run_tests.php)
script: (cd tests; php run_tests.php)
services: mongodb
before_script:
  - mysql -e 'create database myapp_test'
  - mysql myapp_test < tests/test.sql
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
notifications:
  irc: 
    channels:
      - "chat.freenode.net#atk4"
    on_success: always
    on_failure: always
  email: false
